<?php
/**
 * @file
 * Example install file.
 */

/**
 * Implements hook_install().
 */
function konzilo_kickstart_install() {
  // We use seven as our admin theme.
  theme_enable(array('shiny', 'iannis'));
  $variables = array(
    'admin_theme' => 'shiny',
    'theme_default' => 'iannis',
    'node_admin_theme' => 1,
  );
  foreach ($variables as $key => $variable) {
    variable_set($key, $variable);
  }
}
