<?php
/**
 * @file
 * Code for the konzilo_base feature.
 */

include_once 'konzilo_base.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function konzilo_base_ctools_plugin_directory($module, $plugin) {
  if (($module == 'panelizer'  || $module == 'page_manager' || $module == 'panels' || $module == 'ctools' || $module == 'stylizer') && !empty($plugin)) {
    return "plugins/$plugin";
  }
}
