<?php
/**
 * @file
 * Code for the konzilo_base feature.
 */

include_once 'konzilo_base.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function konzilo_base_ctools_plugin_directory($module, $plugin) {
  if (($module == 'panelizer'  || $module == 'page_manager' || $module == 'panels' || $module == 'ctools' || $module == 'stylizer') && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implementation of hook_menu()
 */
function konzilo_base_menu() {
  $items = array();
  $items['admin/config/media/konzilo-settings'] = array(
    'title' => 'Konzilo page settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('konzilo_base_konzilo_page_settings'),
    'access arguments' => array('administer konzilo page settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_permission()
 */
function konzilo_base_permission() {
  return array(
    'administer konzilo page settings' => array(
      'title' => t('Administer Konzilo page settings'),
      'description' => t('Perform settings for Konzilo kickstart page elements'),
    ),
  );
}

/**
 * Menu callback for konzilo page settings
 */
function konzilo_base_konzilo_page_settings() {
  $form = array();

  $form['footer'] = array(
      '#type' => 'vertical_tabs',
  );

  $form['footer']['footer_top'] = array(
      '#type' => 'fieldset',
      '#title' => t('Footer Top'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
  );

  $form['footer']['footer_top']['konzilo_page_logo'] = array(
      '#type' => 'textfield',
      '#title' => t('Logotype path'),
      '#default_value' => variable_get('konzilo_page_logo', ''),
      '#size' => 90,
      '#maxlength' => 255,
  );

  $konzilo_page_address = variable_get('konzilo_page_address');
  $form['footer']['footer_top']['konzilo_page_address'] = array(
    '#type' => 'text_format',
    '#title' => t('Address'),
    '#default_value' => $konzilo_page_address['value'],
    '#rows' => 5,
    '#format' => $konzilo_page_address['format'],
  );

  $konzilo_page_contact = variable_get('konzilo_page_contact');
  $form['footer']['footer_top']['konzilo_page_contact'] = array(
    '#type' => 'text_format',
    '#title' => t('Contact'),
    '#default_value' => $konzilo_page_contact['value'],
    '#rows' => 5,
    '#format' => $konzilo_page_contact['format'],
  );

  $form['footer']['footer_top']['socialmedia'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social media links'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
//  $form['socialmedia']['header'] = array(
//    '#type' => 'textfield',
//    '#title' => t('Social media header'),
//    '#default_value' => $conf['header'],
//    '#size' => 90,
//    '#maxlength' => 255,
//  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_facebook'] = array(
    '#type' => 'textfield',
    '#title' => t('Facebook URL'),
    '#default_value' => variable_get('konzilo_page_facebook', ''),
    '#size' => 90,
    '#maxlength' => 255,
  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_twitter'] = array(
    '#type' => 'textfield',
    '#title' => t('Twitter URL'),
    '#default_value' => variable_get('konzilo_page_twitter', ''),
    '#size' => 90,
    '#maxlength' => 255,
  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_instagram'] = array(
    '#type' => 'textfield',
    '#title' => t('Instagram URL'),
    '#default_value' => variable_get('konzilo_page_instagram', ''),
    '#size' => 90,
    '#maxlength' => 255,
  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_linkedin'] = array(
      '#type' => 'textfield',
      '#title' => t('LinkedIn URL'),
      '#default_value' => variable_get('konzilo_page_linkedin', ''),
      '#size' => 90,
      '#maxlength' => 255,
  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_googleplus'] = array(
      '#type' => 'textfield',
      '#title' => t('Google+ URL'),
      '#default_value' => variable_get('konzilo_page_googleplus', ''),
      '#size' => 90,
      '#maxlength' => 255,
  );
  $form['footer']['footer_top']['socialmedia']['konzilo_page_rss'] = array(
      '#type' => 'textfield',
      '#title' => t('RSS URL'),
      '#default_value' => variable_get('konzilo_page_rss', ''),
      '#size' => 90,
      '#maxlength' => 255,
  );


  $form['footer']['footer_bottom'] = array(
      '#type' => 'fieldset',
      '#title' => t('Footer Bottom'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
  );

  $konzilo_page_footer_bottom_left = variable_get('konzilo_page_footer_bottom_left');
  $form['footer']['footer_bottom']['konzilo_page_footer_bottom_left'] = array(
      '#type' => 'text_format',
      '#title' => t('Footer bottom left'),
      '#default_value' => $konzilo_page_footer_bottom_left['value'],
      '#rows' => 3,
      '#format' => $konzilo_page_footer_bottom_left['format'],
  );

  $konzilo_page_footer_bottom_right = variable_get('konzilo_page_footer_bottom_right');
  $form['footer']['footer_bottom']['konzilo_page_footer_bottom_right'] = array(
      '#type' => 'text_format',
      '#title' => t('Fotter bottom right'),
      '#default_value' => $konzilo_page_footer_bottom_right['value'],
      '#rows' => 3,
      '#format' => $konzilo_page_footer_bottom_right['format'],
  );

  return system_settings_form($form);
}